-- MySQL Script generated by MySQL Workbench
-- Fri Aug 16 18:10:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OpenSky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OpenSky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpenSky` DEFAULT CHARACTER SET utf8 ;
USE `OpenSky` ;


-- -----------------------------------------------------
-- Table `OpenSky`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpenSky`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icao24` VARCHAR(6) NULL,
  `callsign` VARCHAR(45) NULL,
  `origin_country` VARCHAR(45) NULL,
  `on_ground` TINYINT NULL,
  `longitude` FLOAT NULL,
  `latitude` FLOAT NULL,
  `velocity` FLOAT NULL,
  `category` INT NOT NULL,
  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `icao24_UNIQUE` (`icao24` ASC) VISIBLE,
  UNIQUE INDEX `callsign_UNIQUE` (`callsign` ASC) VISIBLE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
